### ISSUE TITLE
generalized configuration

### ISSUE THREAD

**Issue by nhejazi** [CoVPN/correlates_reporting#592]
@youyifong @benkeser Opening discussion here on a few points for moving from the configuration style we currently have to a version sufficiently generalized for the correlates reporting package that is now in development, for use in HVTN 705 and other upcoming analyses. The current configuration setting looks close to what I think we should implement, in the sense of containing _atomic_ configuration variables (each encoding just a single relevant piece of study information). Consider, for example, the following `config.yml` file, which defines timepoints, labels, day-of-analysis generic variable names, assays, etc.

```yml
default: &default
  day_config:
    ph1: ph1
    ph2: ph2
    wt: wt
    EventIndPrimary: EventIndPrimary
    EventTimePrimary: EventTimePrimary
  Dlab: [D57, D29]
  timepoints:
    tinterm: 29
    tpeak: 57
    tlag: 7
  assays: [bindSpike, bindRBD, pseudoneutid50, pseudoneutid80]
  times: [B, Day29, Day57, Delta29overB, Delta57overB, Delta57over29]
  stratify_by: None
  stratify_level: NA
  study_name: General
```

```r
R > default <- config::get()
R > vars <- lapply(default$day_config, function(x) paste(x, default$Dlab, sep = "."))
R > vars
$ph1
[1] "ph1.D57" "ph1.D29"

$ph2
[1] "ph2.D57" "ph2.D29"

$wt
[1] "wt.D57" "wt.D29"

$EventIndPrimary
[1] "EventIndPrimary.D57" "EventIndPrimary.D29"

$EventTimePrimary
[1] "EventTimePrimary.D57" "EventTimePrimary.D29"
```
In the above, each element of the named list `vars` now contains the relevant variables / variable names to be used in an analysis. Specifically, one need only loop over `default$Dlab` (which could have been length one, for a single time point analysis), retrieving as needed the primary event variable name or primary event indicator name (similarly with weights, etc.) to be used in a given analysis. Importantly, note that we do not duplicate variable names across study days, but treat the day-of-analysis variables as generics from which the to-be-used analysis variables are derived. This promotes the use of atomic configuration parameters, from which analysis-ready variables can be _derived_.

By implementing something analogous to this in a top level script (either directly in `_common.R` or similar), we can ensure that variables required for a given analysis (e.g., Moderna, ENSEMBLE) are available across all analyses, which would avoid the need for possibly duplicating logic that might appear in individual modules (e.g., https://github.com/CoVPN/correlates_reporting/blob/master/cor_coxph/code/cor_coxph.R#L24-L33, which is just an example -- basically, this snippet would just be moved to a higher-level script like that).
